version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: movie-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=lalala
      - MYSQL_USER=db
      - MYSQL_PASSWORD=123
    volumes:
      - db_data:/var/lib/mysql
      - ./movies.sql:/docker-entrypoint-initdb.d/movies.sql
    ports:
      - 3306:3306
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 13s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nahiyan83bjit/movie-wiki:stable
    container_name: movie-app
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:

networks:
  mynetwork: